import mongoose from "mongoose";

const runningMovieSchema = new mongoose.Schema({
    movie_id:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    language:{
        type:String,
        required:true
    },
    overview:{
        type:String,
        default:"UNAVAILABLE"
    },
    release_date:{
        type:Date,
        required:true
    },
    popularity:{
        type:Number,
        default:0
    },
    rating:{
        type:Number,
        default:0
    },
    genres:{
        type:Array,
        default:[]
    },
    video_link:{
        type:String,
        default:null
    },
    runtime:{
        type:Number,
        default:0
    },
    backdrop_path:{
        type:String,
        required:true
    },
    poster_path:{
        type:String,
        required:true
    },
    cast:{
        type:Array,
    },
    crew:{
        type:Array,
    },
    isDisabled:{
        type:Boolean,
    },
    isAssigned:{
        type:Boolean,
    },
    enroll_from:{
        type:Date,
        required:true
    },
    enroll_to:{
        type:Date,
        required:true
    },
    status:{
        type:String,
        enum:['RUNNING','REMOVED'],
        default:'RUNNING'
    }
})

const soundSchema = new mongoose.Schema({
    front:{
        type:Number,
        default:0
    },
    rear:{
        type:Number,
        default:0
    },
    left:{
        type:Number,
        default:0
    },
    right:{
        type:Number,
        default:0
    },
    center:{
        type:Number,
        default:0
    },
    subwoofers:{
        type:Number,
        default:0
    }
})

const screenSchema = new mongoose.Schema({
    name:{
        type:String,
        default:"SCREEN"
    },
    running_movies:[{
        type:runningMovieSchema
    }],
    tiers:[{
        name:{
            type:String,
            required:true
        },
        seats:{
            type:Number,
            required:true
        },
        rate:{
            type:Number,
            required:true
        },
        order:{
            type:Number,
        },
        horizontal_partition:{
            type:Number,
            default:0
        },
        columns:{
            type:Number,
            default:0
        },
        layout:[{
            type:Object
        }]
    }],
    showtimes:[{
        showtime:{
            type:String
        },
        movie_id:{
            type:String
        }
    }],
    sound_setup:{
        type:soundSchema
    },

})

export default mongoose.model('screen',screenSchema)