apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollin-booking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking
        image: asia-south1-docker.pkg.dev/rollin-deployment/kiran6177/rollin-booking:latest
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: PORT
        - name: JWT_AUTHSECRET
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: JWT_AUTHSECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: JWT_REFRESH_SECRET
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: S3_BUCKET_NAME
        - name: S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: S3_BUCKET_REGION
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: S3_ACCESS_KEY
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: S3_SECRET_ACCESS_KEY
        - name: CASHFREE_APP_ID
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: CASHFREE_APP_ID
        - name: CASHFREE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: CASHFREE_SECRET_KEY
        - name: MONGOURL
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: MONGOURL
        resources:
          requests:
            cpu: "100m"  
            memory: "256Mi"  
          limits:
            cpu: "200m"  
            memory: "512Mi"
        ports:
        - containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: booking-svc
spec:
  selector:
    app: booking
  ports:
  - name: booking
    protocol: TCP
    port: 4004
    targetPort: 4004
