apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kir4ns6177@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rollin-tls
  namespace: default
spec:
  secretName: rollin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: womensnest.online
  dnsNames:
    - womensnest.online
#RUN FOR CERTIFICATE INSTALL -  https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
