apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/connection-proxy-header: "true"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/websocket-services: "auth-svc"
spec:
  rules:
  - host: rollin.online
    http:
      paths:
      - pathType: Prefix
        path: "/api/auth/?(.*)"
        backend:
          service:
            name: auth-svc
            port:
             number: 4001

