apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollin-movie-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: kiran6177/rollin-movie
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: PORT
        - name: JWT_AUTHSECRET
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: JWT_AUTHSECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: JWT_REFRESH_SECRET
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: S3_BUCKET_NAME
        - name: S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: S3_BUCKET_REGION
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: S3_ACCESS_KEY
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: S3_SECRET_ACCESS_KEY
        - name: TMDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: TMDB_TOKEN
        - name: MONGOURL
          valueFrom:
            secretKeyRef:
              name: movie-secret
              key: MONGOURL
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: movie-svc
spec:
  selector:
    app: movie
  ports:
  - name: movie
    protocol: TCP
    port: 4002
    targetPort: 4002