apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollin-theatre-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theatre
  template:
    metadata:
      labels:
        app: theatre
    spec:
      containers:
      - name: theatre
        image: asia-south1-docker.pkg.dev/rollin-deployment/kiran6177/rollin-theatre
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: PORT
        - name: JWT_AUTHSECRET
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: JWT_AUTHSECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: JWT_REFRESH_SECRET
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: S3_BUCKET_NAME
        - name: S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: S3_BUCKET_REGION
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: S3_ACCESS_KEY
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: S3_SECRET_ACCESS_KEY
        - name: MONGOURL
          valueFrom:
            secretKeyRef:
              name: theatre-secret
              key: MONGOURL
        resources:
          requests:
            cpu: "150m"  
            memory: "256Mi"  
          limits:
            cpu: "150m"  
            memory: "256Mi"
        ports:
        - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: theatre-svc
spec:
  selector:
    app: theatre
  ports:
  - name: theatre
    protocol: TCP
    port: 4003
    targetPort: 4003