name: Build & Deploy auth-svc

on:
  push:
    branches: 
      - "master"
    paths: 
      - "auth-service/**"

jobs:
  built-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          
      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          
      - name: build and push to artifact registry
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          cd auth-service
          docker build -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/kiran6177/rollin-auth .
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/kiran6177/rollin-auth

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          
      - name: deploy to GKE
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials rollin-cluster --zone asia-south1-a --project $GOOGLE_PROJECT_ID
          cd infra/k8s
          kubectl apply -f auth-service.yaml
          kubectl rollout restart deployment/rollin-auth-depl
