name: Build & Deploy Frontend

on:
  push:
    branches: 
      - "master"
    paths: 
      - "frontend/**"

jobs:
  built-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          
      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          
      - name: build and push to artifact registry
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          cd frontend
          docker build \
            --build-arg REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} \
            --build-arg REACT_APP_MAPS_API_KEY=${{ secrets.REACT_APP_MAPS_API_KEY }} \
            --build-arg REACT_APP_MAP_ID=${{ secrets.REACT_APP_MAP_ID }} \
            -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/kiran6177/rollin-client .
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT_ID/kiran6177/rollin-client

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          
      - name: deploy to GKE
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials rollin-cluster --zone asia-south1-a --project $GOOGLE_PROJECT_ID
          cd infra/k8s
          kubectl apply -f client-service.yaml
          kubectl rollout restart deployment/rollin-client-depl
